# Generated by Django 5.0.4 on 2024-04-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_templatedocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatedocument',
            options={'verbose_name': 'Шаблон отчета', 'verbose_name_plural': 'Шаблоны отчетов'},
        ),
    ]
