# Generated by Django 5.0.4 on 2024-04-20 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankrotApp', '0019_alter_arbitrationmanager_options_and_more'),
        ('cases', '0004_alter_templatedocument_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankrotApp.arbitrationmanager', verbose_name='Управляющий'),
        ),
    ]
