# Generated by Django 5.0.4 on 2024-04-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_manager'),
        ('document_generator', '0003_templatedocument_alter_documentform_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateDocument',
        ),
    ]
