# Generated by Django 5.0.4 on 2024-04-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_templatedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='Дело')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.templatedocument', verbose_name='Шаблон документа')),
            ],
            options={
                'verbose_name': 'Форма для формирования документа',
                'verbose_name_plural': 'Формы для формирования документов',
            },
        ),
    ]
