# Generated by Django 5.0.4 on 2024-04-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentform',
            options={'verbose_name': 'Скачивание отчета', 'verbose_name_plural': 'Скачивание отчетов'},
        ),
    ]
