# Generated by Django 5.0.4 on 2024-04-20 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0002_alter_documentform_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('html_code', models.TextField(verbose_name='HTML код шаблона')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
            },
        ),
        migrations.AlterField(
            model_name='documentform',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_generator.templatedocument', verbose_name='Шаблон документа'),
        ),
    ]
