# Generated by Django 5.0.4 on 2024-04-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('snils', models.CharField(max_length=100)),
                ('inn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
