# Generated by Django 5.0.4 on 2024-04-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankrotApp', '0002_alter_client_options_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('location', models.CharField(max_length=100, verbose_name='Местонахождение')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('pledge_info', models.TextField(blank=True, null=True, verbose_name='Сведения о залоге')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('residential', 'Жилая недвижимость'), ('office', 'Офисная недвижимость'), ('warehouse', 'Складская недвижимость'), ('industrial', 'Промышленная недвижимость'), ('hotel', 'Гостиничная недвижимость'), ('commercial', 'Торговая недвижимость')], max_length=20, verbose_name='Вид')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь (кв.м)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('pledge_info', models.TextField(blank=True, null=True, verbose_name='Сведения о залоге')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
            },
        ),
    ]
