# Generated by Django 5.0.4 on 2024-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankrotApp', '0006_alter_account_user_alter_car_user_alter_client_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='client',
            field=models.ManyToManyField(blank=True, to='bankrotApp.client', verbose_name='Клиент'),
        ),
    ]
