# Generated by Django 5.0.4 on 2024-04-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankrotApp', '0007_realestate_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ManyToManyField(blank=True, to='bankrotApp.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ManyToManyField(blank=True, to='bankrotApp.client', verbose_name='Клиент'),
        ),
    ]
