# Generated by Django 5.0.4 on 2024-04-14 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankrotApp', '0014_alter_account_user_alter_car_user_alter_cash_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(verbose_name='История')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankrotApp.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
